import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/components/providers';
import { Box, Paper, Grid } from '@mui/material';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NibiDEX',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Paper
            sx={{
              minHeight: '100vh',
              width: '100vw',
              position: 'absolute',
              top: '0px',
              left: '0px',
              background: 'radial-gradient(#4d663c70 1%, transparent)',
              display: 'flex',
              flexDirection: 'column',
              overflowX: 'hidden'
            }}
          >
            <Navbar />
            <Grid flexGrow={1}>{children}</Grid>
            <Footer />
          </Paper>
        </Providers>
      </body>
    </html>
  );
}
